# Process various excel files

In [1]:
import os

# First, extract the list of all excel files whose name starts with CarbonData
def extract_all_files_to_process():
    all_files = []
    
    # NB : if all the files are in the same directory, os.listdir might be simpler
    for root, _, files in os.walk("."):
        for f in files:
            if f.startswith("CarbonData") and f.endswith(".xlsx"):
                all_files.append(f"{root}/{f}")
                
    return all_files


all_files_to_process = extract_all_files_to_process()
all_files_to_process

['./excel_files/CarbonData_06.xlsx',
 './excel_files/CarbonData_20.xlsx',
 './excel_files/CarbonData_13.xlsx',
 './excel_files/CarbonData_16.xlsx',
 './excel_files/CarbonData_18.xlsx',
 './excel_files/CarbonData_09.xlsx',
 './excel_files/CarbonData_15.xlsx',
 './excel_files/CarbonData_01.xlsx',
 './excel_files/CarbonData_19.xlsx',
 './excel_files/CarbonData_12.xlsx',
 './excel_files/CarbonData_03.xlsx',
 './excel_files/CarbonData_08.xlsx',
 './excel_files/CarbonData_04.xlsx',
 './excel_files/CarbonData_17.xlsx',
 './excel_files/CarbonData_07.xlsx',
 './excel_files/CarbonData_14.xlsx',
 './excel_files/CarbonData_05.xlsx',
 './excel_files/CarbonData_11.xlsx',
 './excel_files/CarbonData_10.xlsx',
 './excel_files/CarbonData_02.xlsx']

In [2]:
import pandas as pd

In [3]:
def process_file(filename):
    output_filename = filename.replace("CarbonData", "DeltaCarbonData")
    
    df = pd.read_excel(filename)

    year_columns = sorted([col for col in df.columns if isinstance(col, int)])
    df_delta = df[['Country Name', 'Country Code']].copy(deep=True)
    
    for year in year_columns[1:]:
        df_delta[year] = df[year]  - df[year-1]
    
    df_delta.to_excel(output_filename)
    
for f in all_files_to_process:
    process_file(f)

In [4]:
df_ref = pd.read_excel('./excel_files/CarbonData_01.xlsx')
df_ref

,Country Name,Country Code,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Afghanistan,AFG,0.045574,0.051518,0.041655,0.060419,0.066583,0.065312,0.128417,0.171862,0.243614,0.296506,0.259295,0.185624,0.146236,0.172897,0.149789,0.131695,0.163295,0.159824
1,Angola,AGO,0.895578,0.924869,0.930263,0.813539,0.821840,0.811754,0.888658,0.939404,0.976184,0.985522,0.950696,1.036294,1.099779,1.135044,1.031811,0.813301,0.777675,0.792137
2,Albania,ALB,1.232379,1.338985,1.404059,1.338209,1.339996,1.393931,1.384311,1.441494,1.527624,1.669423,1.503240,1.533630,1.668337,1.603775,1.557664,1.788786,1.782739,1.692248
3,Andorra,AND,7.566240,7.242416,7.344262,7.353780,6.790543,6.531047,6.439304,6.156687,6.157198,5.850886,5.944654,5.942800,5.807128,6.026182,6.080600,6.104134,6.362975,6.481217
4,United Arab Emirates,ARE,28.501462,27.969270,27.038938,25.382381,22.935104,21.370286,22.011469,19.832349,19.039770,18.509457,19.207801,20.055648,20.051698,21.077642,21.480669,20.769022,18.390678,19.329563
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,Samoa,WSM,0.963664,0.957849,1.063848,1.168471,1.105742,1.098629,0.927593,0.975330,1.021813,1.066843,1.057703,1.048702,1.092498,1.240246,1.542099,1.586830,1.478626,1.522124
187,"Yemen, Rep.",YEM,0.872385,0.984988,1.004601,1.049861,1.059569,1.093386,1.106333,1.180025,1.098258,0.963978,0.858491,1.106688,1.062211,0.511362,0.399364,0.359622,0.341068,0.380633
188,South Africa,ZAF,7.179056,7.557706,8.035040,7.887329,7.832423,8.083508,8.572610,8.007606,8.304084,7.869816,8.077958,8.138264,8.212241,7.669938,7.563739,7.641675,7.515679,7.507736
189,Zambia,ZMB,0.174996,0.184778,0.182674,0.193147,0.179077,0.158363,0.170448,0.188420,0.195502,0.217497,0.278601,0.284058,0.304550,0.312355,0.325115,0.404068,0.445489,0.380717
190,Zimbabwe,ZWE,1.044813,0.849592,0.812818,0.870271,0.808688,0.796350,0.613916,0.618665,0.756041,0.884886,0.915735,0.919824,0.889104,0.899770,0.785441,0.726297,0.857411,0.802979

In [10]:
import matplotlib.pyplot as plt

def draw_graph(df: pd.DataFrame) -> None:
    countries_of_interest = ['France', 'Sweden', 'United States', 'China', 'Germany']
    
    fig = df[df['Country Name'].isin(countries_of_interest)]\
        .set_index('Country Name', drop=True)\
        .drop(columns=['Country Code'])\
        .transpose()\
        .plot(xticks=list(range(2002, 2020)), rot=70)\
        .get_figure()
    fig.savefig('temp.png')
    fig.clear()
    
draw_graph(df_ref)

In [11]:
os.listdir('.')

['temp.png',
 'Retrieve_EURIBOR.ipynb',
 'Process_various_excel_files.ipynb',
 'excel_files',
 'euribor.db',
 'Generate_pdf_reports.ipynb',
 'data.csv',
 '.ipynb_checkpoints']

fpdf is not installed within anaconda by default, so you might have to run the following line of code (and restart your kernel)

In [ ]:
%pip install fpdf

In [6]:
from fpdf import FPDF

In [18]:
class PDF(FPDF):
    def __init__(self, df):
        super().__init__()
        self.WIDTH = 210
        self.HEIGHT = 297
        self.df = df
        
    def header(self):
        # Custom logo and positioning
        # Create an `assets` folder and put any wide and short image inside
        # Name the image `logo.png`
        self.set_font('Arial', 'B', 11)
        self.cell(self.WIDTH - 80)
        self.cell(60, 1, 'CO2 emission report', 0, 0, 'R')
        self.ln(20)
        
    def footer(self):
        # Page numbers in the footer
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, 'Page ' + str(self.page_no()), 0, 0, 'C')

    def page_body(self):
        # Determine how many plots there are per page and set positions
        # and margins accordingly
        draw_graph(self.df)
        self.cell(0, 10, f'Extracted from df with shape {self.df.shape}', 0, 0, 'C')
        self.image('temp.png', 15, 25, self.WIDTH - 30)
        os.remove('temp.png')    
            
    def print_page(self):
        # Generates the report
        self.add_page()
        self.page_body()

In [19]:
pdf = PDF(df_ref)

pdf.print_page()
    
pdf.output('SalesRepot.pdf', 'F')

''